%% Plot results of a trained BESS DT model
% The model should be loaded in a variable named 'model'

num_cycles = 9;   % Number of cycles to include in plot (1 - 9)

% Functions to get scenario filename lists are:
% all_fault_ab - A-B faults at each location
% all_fault_bc - B-C faults at each location
% all_fault_ag - A-Gnd faults at each location
% all_fault_abg - A-B-Gnd faults at each location
% all_fault_abc - A-B-C faults at each location
% all_fault_abcg - A-B-C-Gnd faults at each location
% all_bus_faults - All fault types on the bus (location 3)
% all_gen_faults - All faults types at the generator (location 2)
% all_load1_faults - All fault types at load 1 (location 6)
% all_load2_faults - All fault types at load 2 (location 5)
% all_load3_faults - All fault types at load 3 (location 4)
% all_nominal_events - All nominal events (load steps and "no event")
% ieee1547_edge_cases - Induction machine vs. prime mover loss vs. "no event"

for demo_scenario_filename = all_fault_ab()   % TODO: Change this function for different plots

  dt_info = DTInfo.read_dt_info(demo_scenario_filename);
  
  figure('WindowState', 'maximized');
  fig_full = demo_model(model, dt_info, num_cycles);
end


%% Helper functions
function [filenames] = all_fault_ab(event_index)
  % Get filenames for line-to-line A-B fault (fault 1) at each location
  arguments
    event_index = 50;
  end
  event_index = max([1, event_index]);
  event_index = min([event_index, 200]);

  filenames = [...
    sprintf("D:/data/training/Fault 1 Location 2/scenario_%d-2.mat", event_index), ...
    sprintf("D:/data/training/Fault 1 Location 3/scenario_%d-13.mat", event_index), ...
    sprintf("D:/data/training/Fault 1 Location 4/scenario_%d-125.mat", event_index), ...
    sprintf("D:/data/training/Fault 1 Location 5/scenario_%d-88.mat", event_index), ...
    sprintf("D:/data/training/Fault 1 Location 6/scenario_%d-51.mat", event_index), ...
  ];
end

function [filenames] = all_fault_bc(event_index)
  % Get filenames for line-to-line B-C fault (fault 1) at each location
  arguments
    event_index = 50;
  end
  event_index = max([1, event_index]);
  event_index = min([event_index, 200]);

  filenames = [...
    sprintf("D:/data/training/Fault 2 Location 2/scenario_%d-3.mat", event_index), ...
    sprintf("D:/data/training/Fault 2 Location 3/scenario_%d-14.mat", event_index), ...
    sprintf("D:/data/training/Fault 2 Location 4/scenario_%d-126.mat", event_index), ...
    sprintf("D:/data/training/Fault 2 Location 5/scenario_%d-89.mat", event_index), ...
    sprintf("D:/data/training/Fault 2 Location 6/scenario_%d-52.mat", event_index), ...
  ];
end

function [filenames] = all_fault_ag(event_index)
  % Get filenames for line-to-ground A-G fault (fault 4) at each location
  arguments
    event_index = 50;
  end
  event_index = max([1, event_index]);
  event_index = min([event_index, 200]);

  filenames = [...
    sprintf("D:/data/training/Fault 4 Location 2/scenario_%d-5.mat", event_index), ...
    sprintf("D:/data/training/Fault 4 Location 3/scenario_%d-16.mat", event_index), ...
    sprintf("D:/data/training/Fault 4 Location 4/scenario_%d-128.mat", event_index), ...
    sprintf("D:/data/training/Fault 4 Location 5/scenario_%d-91.mat", event_index), ...
    sprintf("D:/data/training/Fault 4 Location 6/scenario_%d-54.mat", event_index), ...
  ];
end

function [filenames] = all_fault_abg(event_index)
  % Get filenames for line-line-ground A-B-G fault (fault 7) at each location
  arguments
    event_index = 50;
  end
  event_index = max([1, event_index]);
  event_index = min([event_index, 200]);

  filenames = [...
    sprintf("D:/data/training/Fault 7 Location 2/scenario_%d-8.mat", event_index), ...
    sprintf("D:/data/training/Fault 7 Location 3/scenario_%d-19.mat", event_index), ...
    sprintf("D:/data/training/Fault 7 Location 4/scenario_%d-131.mat", event_index), ...
    sprintf("D:/data/training/Fault 7 Location 5/scenario_%d-94.mat", event_index), ...
    sprintf("D:/data/training/Fault 7 Location 6/scenario_%d-57.mat", event_index), ...
  ];
end

function [filenames] = all_fault_abc(event_index)
  % Get filenames for three line fault (fault 11) at each location
  arguments
    event_index = 50;
  end
  event_index = max([1, event_index]);
  event_index = min([event_index, 200]);

  filenames = [...
    sprintf("D:/data/training/Fault 11 Location 2/scenario_%d-12.mat", event_index), ...
    sprintf("D:/data/training/Fault 11 Location 3/scenario_%d-23.mat", event_index), ...
    sprintf("D:/data/training/Fault 11 Location 4/scenario_%d-135.mat", event_index), ...
    sprintf("D:/data/training/Fault 11 Location 5/scenario_%d-98.mat", event_index), ...
    sprintf("D:/data/training/Fault 11 Location 6/scenario_%d-61.mat", event_index), ...
  ];
end

function [filenames] = all_fault_abcg(event_index)
  % Get filenames for three line-to-ground fault (fault 10) at each location
  arguments
    event_index = 50;
  end
  event_index = max([1, event_index]);
  event_index = min([event_index, 200]);

  filenames = [...
    sprintf("D:/data/training/Fault 10 Location 2/scenario_%d-11.mat", event_index), ...
    sprintf("D:/data/training/Fault 10 Location 3/scenario_%d-22.mat", event_index), ...
    sprintf("D:/data/training/Fault 10 Location 4/scenario_%d-134.mat", event_index), ...
    sprintf("D:/data/training/Fault 10 Location 5/scenario_%d-97.mat", event_index), ...
    sprintf("D:/data/training/Fault 10 Location 6/scenario_%d-60.mat", event_index), ...
  ];
end

function [filenames] = all_bus_faults(event_index)
  % Get filenames for each fault type on the bus
  arguments
    event_index = 50;
  end
  event_index = max([1, event_index]);
  event_index = min([event_index, 200]);

  filenames = [...
    sprintf("D:/data/training/Fault 1 Location 3/scenario_%d-13.mat", event_index), ...
    sprintf("D:/data/training/Fault 2 Location 3/scenario_%d-14.mat", event_index), ...
    sprintf("D:/data/training/Fault 3 Location 3/scenario_%d-15.mat", event_index), ...
    sprintf("D:/data/training/Fault 4 Location 3/scenario_%d-16.mat", event_index), ...
    sprintf("D:/data/training/Fault 5 Location 3/scenario_%d-17.mat", event_index), ...
    sprintf("D:/data/training/Fault 6 Location 3/scenario_%d-18.mat", event_index), ...
    sprintf("D:/data/training/Fault 7 Location 3/scenario_%d-19.mat", event_index), ...
    sprintf("D:/data/training/Fault 8 Location 3/scenario_%d-20.mat", event_index), ...
    sprintf("D:/data/training/Fault 9 Location 3/scenario_%d-21.mat", event_index), ...
    sprintf("D:/data/training/Fault 10 Location 3/scenario_%d-22.mat", event_index), ...
    sprintf("D:/data/training/Fault 11 Location 3/scenario_%d-23.mat", event_index), ...
  ];
end

function [filenames] = all_gen_faults(event_index)
  % Get filenames for each fault type at the generator
  arguments
    event_index = 50;
  end
  event_index = max([1, event_index]);
  event_index = min([event_index, 200]);

  filenames = [...
    sprintf("D:/data/training/Fault 1 Location 2/scenario_%d-2.mat", event_index), ...
    sprintf("D:/data/training/Fault 2 Location 2/scenario_%d-3.mat", event_index), ...
    sprintf("D:/data/training/Fault 3 Location 2/scenario_%d-4.mat", event_index), ...
    sprintf("D:/data/training/Fault 4 Location 2/scenario_%d-5.mat", event_index), ...
    sprintf("D:/data/training/Fault 5 Location 2/scenario_%d-6.mat", event_index), ...
    sprintf("D:/data/training/Fault 6 Location 2/scenario_%d-7.mat", event_index), ...
    sprintf("D:/data/training/Fault 7 Location 2/scenario_%d-8.mat", event_index), ...
    sprintf("D:/data/training/Fault 8 Location 2/scenario_%d-9.mat", event_index), ...
    sprintf("D:/data/training/Fault 9 Location 2/scenario_%d-10.mat", event_index), ...
    sprintf("D:/data/training/Fault 10 Location 2/scenario_%d-11.mat", event_index), ...
    sprintf("D:/data/training/Fault 11 Location 2/scenario_%d-12.mat", event_index), ...
  ];
end

function [filenames] = all_nominal_events(event_index)
  % Get filenames for each fault type at the generator
  arguments
    event_index = 50;
  end
  event_index = max([1, event_index]);
  event_index = min([event_index, 200]);

  filenames = [...
    sprintf("D:/data/training/Load step 1/scenario_%d-24.mat", event_index), ...
    sprintf("D:/data/training/Load step 2/scenario_%d-25.mat", event_index), ...
    sprintf("D:/data/training/Load step 3/scenario_%d-26.mat", event_index), ...
    sprintf("D:/data/training/No events/scenario_%d-1.mat", event_index), ...
  ];
end

function [filenames] = ieee1547_edge_cases(event_index)
% Get filenames for IEEE 1547 edge cases
  arguments
    event_index = 50;
  end
  event_index = max([1, event_index]);
  event_index = min([event_index, 200]);

  filenames = [...
    sprintf("D:/data/training/Load step 2/scenario_%d-25.mat", event_index), ...
    sprintf("D:/data/training/Prime mover loss/scenario_%d-27.mat", event_index), ... 
    sprintf("D:/data/training/No events/scenario_%d-1.mat", event_index), ...
  ];
end

function [filenames] = all_load1_faults(event_index)
% Get filenames for each fault type by load 1 (location 6)
  arguments
    event_index = 50;
  end
  event_index = max([1, event_index]);
  event_index = min([event_index, 200]);

  filenames = [...
    sprintf("D:/data/training/Fault 1 Location 6/scenario_%d-51.mat", event_index), ...
    sprintf("D:/data/training/Fault 2 Location 6/scenario_%d-52.mat", event_index), ...
    sprintf("D:/data/training/Fault 3 Location 6/scenario_%d-53.mat", event_index), ...
    sprintf("D:/data/training/Fault 4 Location 6/scenario_%d-54.mat", event_index), ...
    sprintf("D:/data/training/Fault 5 Location 6/scenario_%d-55.mat", event_index), ...
    sprintf("D:/data/training/Fault 6 Location 6/scenario_%d-56.mat", event_index), ...
    sprintf("D:/data/training/Fault 7 Location 6/scenario_%d-57.mat", event_index), ...
    sprintf("D:/data/training/Fault 8 Location 6/scenario_%d-58.mat", event_index), ...
    sprintf("D:/data/training/Fault 9 Location 6/scenario_%d-59.mat", event_index), ...
    sprintf("D:/data/training/Fault 10 Location 6/scenario_%d-60.mat", event_index), ...
    sprintf("D:/data/training/Fault 11 Location 6/scenario_%d-61.mat", event_index), ...
  ];
end

function [filenames] = all_load2_faults(event_index)
% Get filenames for each fault type by load 2 (location 5)
  arguments
    event_index = 50;
  end
  event_index = max([1, event_index]);
  event_index = min([event_index, 200]);

  filenames = [...
    sprintf("D:/data/training/Fault 1 Location 5/scenario_%d-88.mat", event_index), ...
    sprintf("D:/data/training/Fault 2 Location 5/scenario_%d-89.mat", event_index), ...
    sprintf("D:/data/training/Fault 3 Location 5/scenario_%d-90.mat", event_index), ...
    sprintf("D:/data/training/Fault 4 Location 5/scenario_%d-91.mat", event_index), ...
    sprintf("D:/data/training/Fault 5 Location 5/scenario_%d-92.mat", event_index), ...
    sprintf("D:/data/training/Fault 6 Location 5/scenario_%d-93.mat", event_index), ...
    sprintf("D:/data/training/Fault 7 Location 5/scenario_%d-94.mat", event_index), ...
    sprintf("D:/data/training/Fault 8 Location 5/scenario_%d-95.mat", event_index), ...
    sprintf("D:/data/training/Fault 9 Location 5/scenario_%d-96.mat", event_index), ...
    sprintf("D:/data/training/Fault 10 Location 5/scenario_%d-97.mat", event_index), ...
    sprintf("D:/data/training/Fault 11 Location 5/scenario_%d-98.mat", event_index), ...
  ];
end

function [filenames] = all_load3_faults(event_index)
% Get filenames for each fault type by load 3 (location 4)
  arguments
    event_index = 50;
  end
  event_index = max([1, event_index]);
  event_index = min([event_index, 200]);

  filenames = [...
    sprintf("D:/data/training/Fault 1 Location 4/scenario_%d-125.mat", event_index), ...
    sprintf("D:/data/training/Fault 2 Location 4/scenario_%d-126.mat", event_index), ...
    sprintf("D:/data/training/Fault 3 Location 4/scenario_%d-127.mat", event_index), ...
    sprintf("D:/data/training/Fault 4 Location 4/scenario_%d-128.mat", event_index), ...
    sprintf("D:/data/training/Fault 5 Location 4/scenario_%d-129.mat", event_index), ...
    sprintf("D:/data/training/Fault 6 Location 4/scenario_%d-130.mat", event_index), ...
    sprintf("D:/data/training/Fault 7 Location 4/scenario_%d-131.mat", event_index), ...
    sprintf("D:/data/training/Fault 8 Location 4/scenario_%d-132.mat", event_index), ...
    sprintf("D:/data/training/Fault 9 Location 4/scenario_%d-133.mat", event_index), ...
    sprintf("D:/data/training/Fault 10 Location 4/scenario_%d-134.mat", event_index), ...
    sprintf("D:/data/training/Fault 11 Location 4/scenario_%d-135.mat", event_index), ...
  ];
end
